deployment:
  tasks:
    - export REPOPATH=/home/dokaplus/github/prod/TotalDomHelperServer 
    - export SITEPATH=/home/dokaplus/totaldomhelper.dokaplus.by 
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH